headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Users\\cosyc\\ai-town\\ai-town\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\cosyc\\ai-town\\ai-town\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\cosyc\\ai-town\\ai-town\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"
access-control-allow-origin = "*"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]