[build]
  command = "npm run build"
  publish = "dist"

# Handle static files first
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Handle all other routes with SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Strong caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
