[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Handle all routes with SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Strong caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    access-control-allow-origin = "*"
